### ISSUE TITLE
cmark_markdown_to_html returns something wrong on the 2nd call

### ISSUE THREAD

**Issue by opennota** [jgm/cmark#6]
I'm calling `cmark_markdown_to_html()` twice in a row, and it seems to return something wrong the second time ([test.c](https://gist.github.com/opennota/8c0417de86705e66f02a)). The program segfaults on the line 23. [Makefile](https://gist.github.com/opennota/a8d3c027c0ff0539fb8b).

Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff786cc4a in strlen () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff786cc4a in strlen () from /lib64/libc.so.6
#1  0x0000000000400a95 in main (argc=1, argv=0x7fffffffdd98) at test.c:23
(gdb) 
```
gcc warnings:
```
$ make clean all
rm -f test
gcc -g -ggdb -o test test.c -I. -L. -lcmark
test.c: In function 'main':
test.c:17:9: warning: assignment makes pointer from integer without a cast [enabled by default]
  result = cmark_markdown_to_html(text, sz);
         ^
test.c:21:9: warning: assignment makes pointer from integer without a cast [enabled by default]
  result = cmark_markdown_to_html(text, sz);
         ^
```

**Comment by opennota** [comment]
Forgot to `#include <cmark.h>`.
